### PR TITLE
vfio: fix compile error

### PR DESCRIPTION
**Pull request by terenceli**
When compiling On Ubuntu 18.04 which rustc version is 1.35.0,
we will get following compile error.

error[E0133]: access to union field is unsafe and requires unsafe
function or block
   --> vfio/src/vfio_pci.rs:391:13
    |
391 |           entry.u.msi.address_lo = route.msi_vector.msg_addr_lo;
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
access to union field
    |
    = note: the field may not be properly initialized: using
uninitialized data will cause undefined behavior

This patch fixes this issue by using unsafe when accessing union field.

Signed-off-by: Li Qiang <liq3ea@163.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
You need to update your `cargo clippy` linters, and the error will go away. Please close the PR if that's the right fix for you.

**Comment by rbradford** [comment]
As @sboeuf this is a Rust toolchain issue related to a very specific, unsupported, version. Latest stable Rust (1.37.0) does not suffer from this issue. Use "rustup" to update your toolchain.

**Comment by terenceli** [comment]
> As @sboeuf this is a Rust toolchain issue related to a very specific, unsupported, version. Latest stable Rust (1.37.0) does not suffer from this issue. Use "rustup" to update your toolchain.

After update the rustc to 1.37.0, there is no error. 

Thanks
